version: '3'

services:
  gladys:
    build:
      context: ./  # Thư mục hiện tại là thư mục docker, nên đặt context là './'
      dockerfile: Dockerfile  # Dockerfile trong thư mục docker
    container_name: gladys
    restart: always
    privileged: true
    network_mode: host
    # cgroup: host
    logging:
      driver: "json-file"
      options:
        max-size: 10m
    environment:
      NODE_ENV: production
      SQLITE_FILE_PATH: /var/lib/gladysassistant/gladys-production.db
      SERVER_PORT: 80
      TZ: Europe/Paris
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/gladysassistant:/var/lib/gladysassistant
      - /dev:/dev
      - /run/udev:/run/udev:ro

  watchtower:
    image: containrrr/watchtower
    restart: always
    container_name: watchtower
    command: --cleanup --include-restarting --exclude gladys
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock